/*
 * generated by Xtext
 */
package org.xtext.bot.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlaRuntimeModule extends org.xtext.bot.language.AbstractBlaRuntimeModule {

}
