/*
 * generated by Xtext
 */
package org.xtext.bot.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BlaStandaloneSetup extends BlaStandaloneSetupGenerated{

	public static void doSetup() {
		new BlaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

