/*
 * generated by Xtext
 */
package org.xtext.bot.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.bot.language.services.BlaGrammarAccess;

public class BlaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BlaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.bot.language.parser.antlr.internal.InternalBlaParser createParser(XtextTokenStream stream) {
		return new org.xtext.bot.language.parser.antlr.internal.InternalBlaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BotLanguage";
	}
	
	public BlaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BlaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
